#!/usr/bin/env python3
import socket
import sys

# Create a UDS socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
server_address = './lcd_daemon'
print('connecting to %s' % (server_address), file=sys.stderr)
try:
	sock.connect(server_address)
except (socket.error, msg):
	print(msg, file=sys.stderr)
	sys.exit(1)

try:
	# Send data
	message = sys.argv[1]
	print('sending "%s"' % message, file=sys.stderr)
	sock.sendall(str.encode(message))

	amount_received = 0
	amount_expected = 2
	
	while amount_received < amount_expected:
		data = sock.recv(1024)
		amount_received += len(data)
		print('received "%s"' % data.decode(), file=sys.stderr)

finally:
	print("closing socket", file=sys.stderr)
	sock.close()